# Change these first
owner: RossKnight # Your GitHub organization or username, where this repository lives
repo: qupptime # The name of this repository

sites:
  - name: Quotynt.eco
    url: https://quotynt.eco
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.quotynt.eco
  # baseUrl: /qupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: https://status.quotynt.eco
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introTitle: "Real-time status of **Quotynt.eco** services and dashboard"
 # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
 # navbar:
 #   - title: Status
 #     href: /$REPO
 #   - title: GitHub
 #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
